#!/usr/bin/env node
// tools/fixtures/build-example.mjs — ships the demo project as the app's built-in example.
//
//   node tools/fixtures/build-example.mjs           # tools/fixtures/demo.mapa.json → js/example-project.js
//   node tools/fixtures/build-example.mjs --check   # exit 1 when js/example-project.js is out of date
//
// demo.mapa.json holds the four maps that mirror the reference slides in docs/reference/ (Lima
// Metropolitana Sur, Lima Cono Sur, Trujillo, Chimbote). The tests load it as a file; the app needs
// it as a classic script (no fetch() on file://), so this writes
//   window.MT_EXAMPLE_PROJECT = { …the project, unchanged… };
// which index.html loads and "Abrir proyecto de ejemplo" opens (MT.app.openExampleProject).
// Re-run it after editing demo.mapa.json (tools/test/data-roundtrip.test.mjs fails when they differ).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..', '..');
const SRC = path.join(HERE, 'demo.mapa.json');
const OUT = path.join(ROOT, 'js', 'example-project.js');

/** The js/example-project.js text for a project object (deterministic: same input → same bytes). */
export function exampleJs(project) {
  if (!project || project.type !== 'mapa-tiendas-project' || !Array.isArray(project.maps) || !project.maps.length) {
    throw new Error('build-example: demo.mapa.json is not a mapa-tiendas project with maps');
  }
  // JSON is valid JavaScript; escape "</" and the two line separators so the file is safe anywhere.
  const BS = String.fromCharCode(92); // backslash
  const json = JSON.stringify(project, null, 2).replace(/<\//g, '<' + BS + '/')
    .replace(new RegExp(BS + 'u2028', 'g'), BS + 'u2028').replace(new RegExp(BS + 'u2029', 'g'), BS + 'u2029');
  return '/* js/example-project.js — the built-in example project ("Abrir proyecto de ejemplo"): ' + project.maps.length + ' slides\n' +
    ' * mirroring the reference deck (docs/reference/*.png). GENERATED by tools/fixtures/build-example.mjs from\n' +
    ' * tools/fixtures/demo.mapa.json — edit that file and re-run the script; do not edit this one by hand. */\n' +
    'window.MT_EXAMPLE_PROJECT = ' + json + ';\n';
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const project = JSON.parse(readFileSync(SRC, 'utf8'));
  const js = exampleJs(project);
  if (process.argv.includes('--check')) {
    const cur = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
    if (cur !== js) { console.error('build-example: js/example-project.js is out of date — run node tools/fixtures/build-example.mjs'); process.exit(1); }
    console.error('build-example --check: js/example-project.js is up to date.');
  } else {
    writeFileSync(OUT, js);
    console.error(`js/example-project.js: ${project.maps.length} maps (${project.maps.map((m) => m.title).join(', ')}), ${(Buffer.byteLength(js) / 1024).toFixed(1)} KiB`);
  }
}
