"""tools/fixtures/make-logos.py — TEST FIXTURE logos (simple generated badges, not real brand marks).

    python tools/fixtures/make-logos.py

Writes tools/fixtures/logos.js:  window.MT_LOGOS = { <chainId>: { badge: "data:image/png;base64,...",
wide: "data:..." | undefined }, ... } — same shape as logos/logos.js from the data workflow.
"holi" is intentionally absent so the app's generated fallback badge gets exercised.
"""
import base64, io, os, re
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))

# id: (brand colour, text colour, badge text, wordmark)
CHAINS = {
    "plazavea":    ("#E30613", "#FFFFFF", "pV",    "plazaVea"),
    "tottus":      ("#3F8E2B", "#FFFFFF", "T",     "TOTTUS"),
    "wong":        ("#D52B1E", "#FFFFFF", "W",     "Wong"),
    "metro":       ("#F2B705", "#C8102E", "M",     "Metro"),
    "vivanda":     ("#7A1E3A", "#FFFFFF", "V",     "Vivanda"),
    "tiendas3a":   ("#F37021", "#FFFFFF", "3A",    None),
    "mass":        ("#FFD100", "#111111", "mass",  None),
    "preciouno":   ("#E4002B", "#FFFFFF", "P1",    "PRECIO UNO"),
    "maxiahorro":  ("#D6007E", "#FFFFFF", "MX",    None),
    "dollarcity":  ("#00843D", "#FFFFFF", "D$",    "Dollarcity"),
    "makro":       ("#0B2D8C", "#FFE600", "makro", "makro"),
    "vega":        ("#1BA548", "#FFFFFF", "VG",    None),
    "florayfauna": ("#2B2B2B", "#FFFFFF", "F&F",   "F&F"),
    "tambo":       ("#5B2C83", "#FFD100", "t+",    "tambo+"),
    "oxxo":        ("#DA291C", "#FFD100", "OXXO",  "OXXO"),
}

FONT_CANDIDATES = ["C:/Windows/Fonts/arialbd.ttf", "C:/Windows/Fonts/segoeuib.ttf",
                   "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", "/Library/Fonts/Arial Bold.ttf"]


def font(size):
    for f in FONT_CANDIDATES:
        if os.path.exists(f):
            return ImageFont.truetype(f, size)
    return ImageFont.load_default()


def fit_text(draw, text, max_w, max_h, start):
    size = start
    while size > 10:
        f = font(size)
        l, t, r, b = draw.textbbox((0, 0), text, font=f)
        if r - l <= max_w and b - t <= max_h:
            return f, (l, t, r, b)
        size -= 4
    f = font(size)
    return f, draw.textbbox((0, 0), text, font=f)


def data_uri(img):
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def badge(color, fg, text):
    s = 256
    img = Image.new("RGBA", (s, s), color)
    d = ImageDraw.Draw(img)
    f, (l, t, r, b) = fit_text(d, text, 170, 120, 150)
    d.text(((s - (r - l)) / 2 - l, (s - (b - t)) / 2 - t), text, font=f, fill=fg)
    return img


def wide(color, text):
    f = font(120)
    tmp = ImageDraw.Draw(Image.new("RGBA", (10, 10)))
    l, t, r, b = tmp.textbbox((0, 0), text, font=f)
    img = Image.new("RGBA", (r - l + 24, b - t + 24), (0, 0, 0, 0))
    ImageDraw.Draw(img).text((12 - l, 12 - t), text, font=f, fill=color)
    if img.width > 512:
        img = img.resize((512, round(img.height * 512 / img.width)), Image.LANCZOS)
    return img


def main():
    entries = []
    for cid, (color, fg, text, word) in CHAINS.items():
        parts = [f'badge: "{data_uri(badge(color, fg, text))}"']
        if word:
            parts.append(f'wide: "{data_uri(wide(color, word))}"')
        entries.append(f'  {cid}: {{ {", ".join(parts)} }}')
    js = ("// TEST FIXTURE — generated by tools/fixtures/make-logos.py (simple badges, not real logos).\n"
          "// 'holi' intentionally missing to exercise the generated fallback badge.\n"
          "window.MT_LOGOS = {\n" + ",\n".join(entries) + "\n};\n")
    with open(os.path.join(HERE, "logos.js"), "w", encoding="utf-8") as fh:
        fh.write(js)
    print(f"logos.js: {len(CHAINS)} chains, {len(js) // 1024} KB")


if __name__ == "__main__":
    main()
