#!/usr/bin/env node
/**
 * tools/build-logos.mjs — bundles the chain logos as data URIs (SPEC §3.3).
 *
 *   node tools/build-logos.mjs
 *
 * Reads   logos/<id>.png       square badge mark, 512×512   → downscaled to 256×256
 *         logos/<id>-wide.png  horizontal wordmark (optional, ≤ 512 px wide, kept at its size)
 * Writes  logos/logos.js       window.MT_LOGOS = { <id>: { badge: "data:image/png;base64,…" | null,
 *                                                         wide: "data:image/png;base64,…" | null }, … }
 *
 * Every chain of tools/seed/chains/*.json gets an entry (badge null when logos/<id>.png is missing →
 * the app draws its generated name badge); extra logos/<id>.png files are included too.
 * Resizing uses Python + Pillow (LANCZOS, optimized PNG, no metadata): `python`/`python3`/`py` on PATH,
 * or set the MT_PYTHON environment variable. Same PNGs + same Pillow version → byte-identical logos.js.
 * Logo sources and licences: tools/seed/chains/<id>.json → logoSources.
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const LOGOS = path.join(ROOT, 'logos');
const CHAINS_DIR = path.join(HERE, 'seed', 'chains');
const OUT = path.join(LOGOS, 'logos.js');
const BADGE_PX = 256;
const WIDE_MAX_W = 512;

const ids = new Set();
if (existsSync(CHAINS_DIR)) {
  for (const f of readdirSync(CHAINS_DIR)) if (f.endsWith('.json')) {
    try { const j = JSON.parse(readFileSync(path.join(CHAINS_DIR, f), 'utf8')); if (j.id) ids.add(j.id); } catch { /* not a chain file */ }
  }
}
for (const f of readdirSync(LOGOS)) { const m = /^([a-z0-9]+)\.png$/.exec(f); if (m) ids.add(m[1]); }
const jobs = [...ids].sort().map((id) => {
  const badge = path.join(LOGOS, `${id}.png`), wide = path.join(LOGOS, `${id}-wide.png`);
  return { id, badge: existsSync(badge) ? badge : null, wide: existsSync(wide) ? wide : null };
});

const PY = String.raw`
import sys, json, io, base64
from PIL import Image
jobs = json.load(sys.stdin)
BADGE, WIDE = int(sys.argv[1]), int(sys.argv[2])
def enc(im):
    buf = io.BytesIO()
    im.save(buf, format='PNG', optimize=True)
    return base64.b64encode(buf.getvalue()).decode('ascii')
out = {}
for j in jobs:
    r = {'badge': None, 'wide': None, 'info': {}}
    if j['badge']:
        im = Image.open(j['badge']); im.load(); im = im.convert('RGBA')
        r['info']['badgeSrc'] = list(im.size)
        if im.size[0] != im.size[1]:
            side = max(im.size); sq = Image.new('RGBA', (side, side), (0, 0, 0, 0))
            sq.paste(im, ((side - im.size[0]) // 2, (side - im.size[1]) // 2)); im = sq
        if im.size[0] != BADGE:
            im = im.resize((BADGE, BADGE), Image.LANCZOS)
        r['badge'] = enc(im)
    if j['wide']:
        im = Image.open(j['wide']); im.load(); im = im.convert('RGBA')
        r['info']['wideSrc'] = list(im.size)
        if im.size[0] > WIDE:
            h = max(1, round(im.size[1] * WIDE / im.size[0])); im = im.resize((WIDE, h), Image.LANCZOS)
        r['info']['wide'] = list(im.size)
        r['wide'] = enc(im)
    out[j['id']] = r
json.dump(out, sys.stdout)
`;
// MT_PYTHON overrides; otherwise the usual launchers are tried in order.
const candidates = process.env.MT_PYTHON ? [process.env.MT_PYTHON] : ['python', 'python3', 'py'];
let res = null, lastErr = null;
for (const python of candidates) {
  try {
    res = JSON.parse(execFileSync(python, ['-c', PY, String(BADGE_PX), String(WIDE_MAX_W)],
      { input: JSON.stringify(jobs), maxBuffer: 256 * 1024 * 1024, stdio: ['pipe', 'pipe', 'pipe'] }).toString('utf8'));
    break;
  } catch (err) { lastErr = err; }
}
if (!res) {
  console.error(`build-logos: Python + Pillow failed (tried ${candidates.join(', ')}). Install Pillow (pip install pillow) or set MT_PYTHON.\n${lastErr && lastErr.message}`);
  process.exit(1);
}

const lines = jobs.map(({ id }) => {
  const r = res[id];
  const badge = r.badge ? `data:image/png;base64,${r.badge}` : null;
  const wide = r.wide ? `data:image/png;base64,${r.wide}` : null;
  return `  ${JSON.stringify(id)}:{"badge":${JSON.stringify(badge)},"wide":${JSON.stringify(wide)}}`;
});
const js = '/* mapa-tiendas — chain logos as data URIs (SPEC §3.3). Generated by tools/build-logos.mjs from logos/<id>.png\n' +
  ` * (badge, downscaled to ${BADGE_PX}×${BADGE_PX}) and logos/<id>-wide.png (wordmark, ≤ ${WIDE_MAX_W} px wide). Sources: tools/seed/chains/<id>.json. */\n` +
  'window.MT_LOGOS = {\n' + lines.join(',\n') + '\n};\n';
writeFileSync(OUT, js);

const missing = jobs.filter((j) => !j.badge).map((j) => j.id);
const noWide = jobs.filter((j) => !j.wide).map((j) => j.id);
console.error(`logos.js: ${jobs.length} chains, ${(Buffer.byteLength(js) / 1024).toFixed(0)} KiB` +
  `${missing.length ? `; no badge (generated in app): ${missing.join(', ')}` : ''}${noWide.length ? `; no wide logo: ${noWide.join(', ')}` : ''}`);
for (const j of jobs) {
  const i = res[j.id].info;
  console.error(`  ${j.id.padEnd(12)} badge ${i.badgeSrc ? i.badgeSrc.join('×') + ' → ' + BADGE_PX + '×' + BADGE_PX : '—'}  wide ${i.wide ? i.wideSrc.join('×') + (i.wideSrc[0] !== i.wide[0] ? ' → ' + i.wide.join('×') : '') : '—'}`);
}
