#!/usr/bin/env node
// tools/build-fonts.mjs — embeds the vendored WOFF2 fonts into vendor/fonts/fonts.css as data URIs.
//
//   node tools/build-fonts.mjs
//
// Why data URIs: @font-face url() loads are CORS-mode requests whose file:// rules differ between
// browsers. Inlined fonts work everywhere (file://, GitHub Pages) with no extra request, so the slide
// canvas renderer can rely on Carlito (metric-compatible with Calibri, which PowerPoint uses) for a
// faithful preview.

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIR = path.join(ROOT, 'vendor', 'fonts');
// Latin subset (U+0000-00FF etc.) covers Spanish: á é í ó ú ñ ü ¿ ¡ « ».
const LATIN = 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

const faces = [
  { family: 'Instrument Sans', file: 'instrument-sans-latin-wght-normal.woff2', weight: '400 700' },
  { family: 'Bricolage Grotesque', file: 'bricolage-grotesque-latin-wght-normal.woff2', weight: '200 800' },
  { family: 'Carlito', file: 'carlito-latin-400-normal.woff2', weight: '400' },
  { family: 'Carlito', file: 'carlito-latin-700-normal.woff2', weight: '700' },
];

let css = `/* GENERATED by tools/build-fonts.mjs — do not edit. Fonts: SIL Open Font License 1.1
   (see LICENSE-*.txt in this folder). Instrument Sans = UI, Bricolage Grotesque = display,
   Carlito = Calibri-metric slide font for canvas previews/exports. */\n`;
for (const f of faces) {
  const b64 = readFileSync(path.join(DIR, f.file)).toString('base64');
  css += `@font-face{font-family:'${f.family}';font-style:normal;font-display:block;font-weight:${f.weight};` +
    `src:url(data:font/woff2;base64,${b64}) format('woff2');unicode-range:${LATIN};}\n`;
}
writeFileSync(path.join(DIR, 'fonts.css'), css);
console.log(`vendor/fonts/fonts.css: ${(css.length / 1024).toFixed(0)} KB, ${faces.length} faces`);
